# permissions for end users to edit libvirts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: libvirt-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: atmosphere-operator
    app.kubernetes.io/part-of: atmosphere-operator
    app.kubernetes.io/managed-by: kustomize
  name: libvirt-editor-role
rules:
- apiGroups:
  - infra.atmosphere.vexxhost.com
  resources:
  - libvirts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.atmosphere.vexxhost.com
  resources:
  - libvirts/status
  verbs:
  - get
