# permissions for end users to edit designates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: designate-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: atmosphere-operator
    app.kubernetes.io/part-of: atmosphere-operator
    app.kubernetes.io/managed-by: kustomize
  name: designate-editor-role
rules:
- apiGroups:
  - openstack.atmosphere.vexxhost.com
  resources:
  - designates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.atmosphere.vexxhost.com
  resources:
  - designates/status
  verbs:
  - get
