# permissions for end users to view octavia.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: octavia-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: atmosphere-operator
    app.kubernetes.io/part-of: atmosphere-operator
    app.kubernetes.io/managed-by: kustomize
  name: octavia-viewer-role
rules:
- apiGroups:
  - openstack.atmosphere.vexxhost.com
  resources:
  - octavia
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openstack.atmosphere.vexxhost.com
  resources:
  - octavia/status
  verbs:
  - get
