# permissions for end users to view ironics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ironic-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: atmosphere-operator
    app.kubernetes.io/part-of: atmosphere-operator
    app.kubernetes.io/managed-by: kustomize
  name: ironic-viewer-role
rules:
- apiGroups:
  - openstack.atmosphere.vexxhost.com
  resources:
  - ironics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openstack.atmosphere.vexxhost.com
  resources:
  - ironics/status
  verbs:
  - get
