# permissions for end users to view neutrons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: neutron-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: atmosphere-operator
    app.kubernetes.io/part-of: atmosphere-operator
    app.kubernetes.io/managed-by: kustomize
  name: neutron-viewer-role
rules:
- apiGroups:
  - openstack.atmosphere.vexxhost.com
  resources:
  - neutrons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openstack.atmosphere.vexxhost.com
  resources:
  - neutrons/status
  verbs:
  - get
