apiVersion: v1
kind: Secret
metadata:
  name: barbican
type: Opaque
stringData:
  memcache: memcached
  database: db123
  rabbitmq: rabbit123
  keystone: barbican123
  kek: dGhpcnR5X3R3b19ieXRlX2tleWJsYWhibGFoYmxhaGg=
---
apiVersion: infra.atmosphere.vexxhost.com/v1alpha1
kind: RabbitmqCluster
metadata:
  name: barbican
spec: {}
---
apiVersion: openstack.atmosphere.vexxhost.com/v1alpha1
kind: Barbican
metadata:
  name: barbican
spec:
  replicas: 1
  regionName: RegionOne
  ingress:
    host: key-manager.cloud.vexxhost.com
    className: nginx
  keystoneRef:
    name: keystone
  secretsRef:
    name: barbican
  databaseRef:
    name: percona-xtradb
  rabbitmqRef:
    name: barbican
  overrides:
    conf:
      keystone:
        DEFAULT:
          foo: bar
