---
apiVersion: v1
kind: Secret
metadata:
  name: nova
type: Opaque
stringData:
  memcache: memcached
  database: db123
  rabbitmq: rabbit123
  keystone: nova123
  metadata: metadata123
---
apiVersion: infra.atmosphere.vexxhost.com/v1alpha1
kind: RabbitmqCluster
metadata:
  name: nova
spec: {}
---
apiVersion: openstack.atmosphere.vexxhost.com/v1alpha1
kind: Nova
metadata:
  name: nova
spec:
  replicas: 1
  regionName: RegionOne
  ingress:
    host: compute.cloud.vexxhost.com
    className: nginx
  keystoneRef:
    name: keystone
  secretsRef:
    name: nova
  databaseRef:
    name: percona-xtradb
  rabbitmqRef:
    name: nova
  overrides:
    conf:
      nova:
        DEFAULT:
          foo: bar
