---
apiVersion: v1
kind: Secret
metadata:
  name: neutron
type: Opaque
stringData:
  memcache: memcached
  database: db123
  rabbitmq: rabbit123
  keystone: neutron123
---
apiVersion: infra.atmosphere.vexxhost.com/v1alpha1
kind: RabbitmqCluster
metadata:
  name: neutron
spec: {}
---
apiVersion: openstack.atmosphere.vexxhost.com/v1alpha1
kind: Neutron
metadata:
  name: neutron
spec:
  replicas: 1
  regionName: RegionOne
  ingress:
    host: network.cloud.vexxhost.com
    className: nginx
  keystoneRef:
    name: keystone
  novaRef:
    name: nova
  octaviaRef:
    name: octavia
  designateRef:
    name: designate
  ironicRef:
    name: ironic
  coreDnsRef:
    name: kube-dns
    namespace: kube-system
  secretsRef:
    name: neutron
  databaseRef:
    name: percona-xtradb
  rabbitmqRef:
    name: neutron
  overrides:
    conf:
      auto_bridge_add:
        br-ex: ""
      neutron:
        DEFAULT:
          foo: bar
