---
apiVersion: v1
kind: Secret
metadata:
  name: horizon
type: Opaque
stringData:
  database: horizon123
---
apiVersion: openstack.atmosphere.vexxhost.com/v1alpha1
kind: Horizon
metadata:
  name: horizon
spec:
  replicas: 1
  ingress:
    host: dashboard.cloud.vexxhost.com
    className: nginx
  keystoneRef:
    name: keystone
  databaseRef:
    name: percona-xtradb
  secretsRef:
    name: horizon
