---
apiVersion: v1
kind: Secret
metadata:
  name: designate
type: Opaque
stringData:
  memcache: memcached
  database: db123
  rabbitmq: rabbit123
  keystone: designate123
---
apiVersion: infra.atmosphere.vexxhost.com/v1alpha1
kind: RabbitmqCluster
metadata:
  name: designate
spec: {}
---
apiVersion: openstack.atmosphere.vexxhost.com/v1alpha1
kind: Designate
metadata:
  name: designate
spec:
  replicas: 1
  regionName: RegionOne
  ingress:
    host: dns.cloud.vexxhost.com
    className: nginx
  keystoneRef:
    name: keystone
  secretsRef:
    name: designate
  databaseRef:
    name: percona-xtradb
  rabbitmqRef:
    name: designate
  overrides:
    conf:
      designate:
        DEFAULT:
          foo: bar
