---
apiVersion: v1
kind: Secret
metadata:
  name: keystone
type: Opaque
stringData:
  memcache: memcached
  database: database
  rabbitmq: rabbitmq
  admin: admin
---
apiVersion: infra.atmosphere.vexxhost.com/v1alpha1
kind: RabbitmqCluster
metadata:
  name: keystone
spec: {}
---
apiVersion: openstack.atmosphere.vexxhost.com/v1alpha1
kind: Keystone
metadata:
  name: keystone
spec:
  replicas: 1
  regionName: RegionOne
  ingress:
    host: identity.cloud.vexxhost.com
    className: nginx
  secretsRef:
    name: keystone
  databaseRef:
    name: percona-xtradb
  rabbitmqRef:
    name: keystone
  overrides:
    conf:
      keystone:
        DEFAULT:
          foo: bar
