---
apiVersion: v1
kind: Secret
metadata:
  name: ironic
type: Opaque
stringData:
  memcache: memcached
  database: db123
  rabbitmq: rabbit123
  keystone: ironic123
---
apiVersion: infra.atmosphere.vexxhost.com/v1alpha1
kind: RabbitmqCluster
metadata:
  name: ironic
spec: {}
---
apiVersion: openstack.atmosphere.vexxhost.com/v1alpha1
kind: Ironic
metadata:
  name: ironic
spec:
  replicas: 1
  regionName: RegionOne
  ingress:
    host: baremetal.cloud.vexxhost.com
    className: nginx
  keystoneRef:
    name: keystone
  secretsRef:
    name: ironic
  databaseRef:
    name: percona-xtradb
  rabbitmqRef:
    name: ironic
  overrides:
    conf:
      ironic:
        DEFAULT:
          foo: bar
