# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/infra.atmosphere.vexxhost.com_memcacheds.yaml
- bases/openstack.atmosphere.vexxhost.com_keystones.yaml
- bases/infra.atmosphere.vexxhost.com_rabbitmqclusters.yaml
- bases/openstack.atmosphere.vexxhost.com_barbicans.yaml
- bases/openstack.atmosphere.vexxhost.com_placements.yaml
- bases/infra.atmosphere.vexxhost.com_openvswitches.yaml
- bases/openstack.atmosphere.vexxhost.com_neutrons.yaml
- bases/openstack.atmosphere.vexxhost.com_octavia.yaml
- bases/openstack.atmosphere.vexxhost.com_designates.yaml
- bases/openstack.atmosphere.vexxhost.com_nova.yaml
- bases/openstack.atmosphere.vexxhost.com_ironics.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_memcacheds.yaml
#- patches/webhook_in_keystones.yaml
#- patches/webhook_in_rabbitmqclusters.yaml
#- patches/webhook_in_barbicans.yaml
#- patches/webhook_in_placements.yaml
#- patches/webhook_in_openvswitches.yaml
#- patches/webhook_in_neutrons.yaml
#- patches/webhook_in_octavia.yaml
#- patches/webhook_in_designates.yaml
#- patches/webhook_in_nova.yaml
#- patches/webhook_in_ironics.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_memcacheds.yaml
#- patches/cainjection_in_keystones.yaml
#- patches/cainjection_in_rabbitmqclusters.yaml
#- patches/cainjection_in_barbicans.yaml
#- patches/cainjection_in_placements.yaml
#- patches/cainjection_in_openvswitches.yaml
#- patches/cainjection_in_neutrons.yaml
#- patches/cainjection_in_octavia.yaml
#- patches/cainjection_in_designates.yaml
#- patches/cainjection_in_nova.yaml
#- patches/cainjection_in_ironics.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
